### PR TITLE
Fixes #63 Multiple Set-Cookie not working

### LINKED ISSUE #63: Multiple Set-Cookie not working in hook.js/ts in the Build. Only setting the first cookie.
**Sveltekit version: 1.0.0.next.405
Azure-SWA-adapter-version: ^0.10.0**

In hooks.js if we are sending multiple cookies in response header like this:
```
response.headers.append('Set-Cookie', cookie1);
response.headers.append('Set-Cookie', cookie2);
response.headers.append('Set-Cookie', cookie3);
```
The response header during dev environment looks like this:
```
Set-cookie : cookie1
Set-cookie : cookie2
Set-cookie : cookie3
```
and it sets all cookies. 

But when testing the build either with SWA CLI or deployed app. The response header looks like this:

`Set-Cookie: Cookie1; Cookie2; Cookie3`
This only takes Cookie1 into account and leave the rest.  

I have deployed my app on Vercel with Serverless Function  using Vercel adapter and on Azure with Nodejs adapter. On both , the `Set-Cookie` behave as expected and set all the cookies and response header also looks like this:
```
Set-cookie : cookie1
Set-cookie : cookie2
Set-cookie : cookie3
```

### PR DESCRIPTION
**Pull request by FlippingBinary**
This fixes #63, according to local tests with the SWA cli. SvelteKit returns cookies combined together in a single header, so they have to be split apart and parsed into a structure SWA/Azure understands. I haven't tested this in Azure, but if it doesn't work there it's because of the problems mentioned here: https://github.com/Azure/static-web-apps/issues/278

### CODE REVIEW

File: files/entry.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import { installPolyfills } from '@sveltejs/kit/node/polyfills';
 import { Server } from 'SERVER';
 import { manifest } from 'MANIFEST';
+import { split_cookies_from_headers } from './headers';
```
Comment (geoffrich) [inline files/entry.js:4]: Nit: we use camel case everywhere else in the adapter
```suggestion
import { splitCookiesFromHeaders } from './headers';
```

File: files/entry.js [hunk 2]
```diff
@@ -67,16 +68,13 @@ async function toResponse(rendered) {
 	const { status } = rendered;
 	const resBody = new Uint8Array(await rendered.arrayBuffer());
 
-	/** @type {Record<string, string>} */
-	const resHeaders = {};
-	rendered.headers.forEach((value, key) => {
-		resHeaders[key] = value;
-	});
+	const { headers, cookies } = split_cookies_from_headers(rendered.headers);
```
Comment (geoffrich) [inline files/entry.js:71]:
```suggestion
	const { headers, cookies } = splitCookiesFromHeaders(rendered.headers);
```

File: files/headers.js [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+
+/**
+ * Splits 'set-cookie' headers into individual cookies
+ * @param {Headers} headers
+ * @returns {{
+ *   headers: Record<string, string>,
+ *   cookies: set_cookie_parser.Cookie[]
+ * }}
+ */
+export function split_cookies_from_headers(headers) {
```
Comment (geoffrich) [inline files/headers.js:11]:
```suggestion
export function splitCookiesFromHeaders(headers) {
```

File: test/headers.test.js [hunk 4]
```diff
@@ -0,0 +1,59 @@
+import { installPolyfills } from '@sveltejs/kit/node/polyfills';
+import { expect, describe, test } from 'vitest';
+import { split_cookies_from_headers } from '../files/headers';
```
Comment (geoffrich) [inline test/headers.test.js:3]:
```suggestion
import { splitCookiesFromHeaders } from '../files/headers';
```

File: test/headers.test.js [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+
+installPolyfills();
+
+describe('header processing', () => {
+	test('no cookies', () => {
+		const headers = new Headers();
+		headers.append('Location', '/');
+		headers.append('Content-Type', 'application/json');
+
+		const cookies = split_cookies_from_headers(headers);
```
Comment (geoffrich) [inline test/headers.test.js:13]:
```suggestion
		const cookies = splitCookiesFromHeaders(headers);
```

File: test/headers.test.js [hunk 6]
```diff
@@ -0,0 +1,59 @@
...
+		// https://httpwg.org/specs/rfc7231.html#http.date
+		const exp1 = 'Sun, 06 Nov 1994 08:49:37 GMT';
+		const exp2 = 'Sunday, 06-Nov-94 08:49:37 GMT';
+		const exp3 = 'Sun Nov  6 08:49:37 1994';
+
+		headers.append('Set-Cookie', `key1=val1; Expires=${exp1}`);
+		headers.append('Set-Cookie', `key2=val2; Expires=${exp2}`);
+		headers.append('Set-Cookie', `key3=val3; Expires=${exp3}`);
+
+		const cookies = split_cookies_from_headers(headers);
```
Comment (geoffrich) [inline test/headers.test.js:36]:
```suggestion
		const cookies = splitCookiesFromHeaders(headers);
```

File: test/headers.test.js [hunk 7]
```diff
@@ -0,0 +1,59 @@
...
+					name: 'key1',
+					value: 'val1'
+				},
+				{
+					expires: new Date('1994-11-06T08:49:37.000Z'),
+					name: 'key2',
+					value: 'val2'
+				},
+				{
+					expires: new Date('1994-11-06T13:49:37.000Z'),
```
Comment (geoffrich) [inline test/headers.test.js:52]: This test broke on my machine, assuming timezone issue. Changing to GMT seemed to get around it.
```suggestion
					expires: new Date('1994-11-06T08:49:37.000Z'),
```

File: test/headers.test.js [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+		});
+	});
+
+	test('multiple cookies', () => {
+		const headers = new Headers();
+
+		// https://httpwg.org/specs/rfc7231.html#http.date
+		const exp1 = 'Sun, 06 Nov 1994 08:49:37 GMT';
+		const exp2 = 'Sunday, 06-Nov-94 08:49:37 GMT';
+		const exp3 = 'Sun Nov  6 08:49:37 1994';
```
Comment (geoffrich) [inline test/headers.test.js:30]:
```suggestion
		const exp3 = 'Sun Nov  6 08:49:37 1994 GMT';
```

**Review by geoffrich — COMMENTED** [review]
A couple suggestions to make the test more resilient to running in different time zones
